# syntax=docker/dockerfile:1

## Build
FROM golang:1.19-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

RUN go build -o /content-server

## Deploy
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /content-server /content-server

ENV HTTP_PORT=8080

EXPOSE $HTTP_PORT

USER nonroot:nonroot

ENTRYPOINT ["/content-server"]